# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='sicil_no',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='surveyuser',
            unique_together=set([('sicil_no', 'survey_token')]),
        ),
    ]
